services:
  nicoSWD\SecHeaderCheck\:
    resource: '../src/*'
    exclude: '../src/Application/Command'
    autowire: true
    public: false

  nicoSWD\SecHeaderCheck\Application\Command\:
    resource: '../src/Application/Command'
    autowire: true
    public: true
    tags: [console.command]

  nicoSWD\SecHeaderCheck\Domain\ResultPrinter\ResultPrinterFactory:
    arguments:
      - '@nicoSWD\SecHeaderCheck\Infrastructure\ResultPrinter\JSONResultPrinter'
      - '@nicoSWD\SecHeaderCheck\Infrastructure\ResultPrinter\XMLResultPrinter'

  nicoSWD\SecHeaderCheck\Infrastructure\ResultPrinter\JSONResultPrinter:
    class: nicoSWD\SecHeaderCheck\Infrastructure\ResultPrinter\JSONResultPrinter

  nicoSWD\SecHeaderCheck\Infrastructure\ResultPrinter\XMLResultPrinter:
    class: nicoSWD\SecHeaderCheck\Infrastructure\ResultPrinter\XMLResultPrinter
